version: '3'
services:
  postgres:
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  pg_data: {}
